import {ref} from "vue";

export default {
    divisions: [],
    permanentDistricts: [],
    districts: [],
    upazilas: [],
    permanentUpazilas: [],
    sameAddress: false,
    currentDivisionId: null,
    permanentDivisionId: null,
    currentDistrictId: null,
    permanentDistrictId: null,
    currentUpazilaId: null,
    permanentUpazilaId: null,
    permanent_village: null,
    permanent_post_office: null,
    village: null,
    post_office: null,
    date: new Date().toISOString().substr(0, 10),
    suppliers: [],
    customers: [],
    products: [],
    saleProducts: [],
    searchProducts: ref([]),
    barcodeProduct: {},
    categories: [],
    brands: [],
    units: [],
    cashes: [],
    bankAccounts: [],
    cartProducts: [],
    saleCartProducts: [],
    offerCartProducts: [],
    purchaseCartProducts: [],
    errors: [],
    productSkeleton: false,
    oldSale: {},
    subtotal: 0,
    discount: null,
    vat: null,
    paid: null,
    paid_by: 'cash',
    bank_id: null,
    customer_id: null,
    disabledSaleButton: false,
    from: 'sale',
    order_id: null,
    point_amount: 0,
}
